# Generated by Django 5.1.4 on 2024-12-06 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='awareness_detail',
            fields=[
                ('awareness_detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=1000)),
                ('awareness_type', models.CharField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='electronic_info',
            fields=[
                ('electronic_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('eiin_number', models.CharField(max_length=100)),
                ('serial_numeber', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='missing_person_info',
            fields=[
                ('missing_person_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image_url', models.URLField(max_length=100)),
                ('image_vector', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=100)),
                ('dress', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=1000)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='other_info',
            fields=[
                ('other_info_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('image_url', models.URLField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='crime_detail',
            fields=[
                ('crime_detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crime_type', models.CharField(max_length=100)),
                ('incident_time', models.DateTimeField()),
                ('details', models.CharField(max_length=1000)),
                ('item_type', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('electronic_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.electronic_info')),
                ('other_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.other_info')),
            ],
        ),
        migrations.CreateModel(
            name='verified',
            fields=[
                ('verified_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
                ('fir_number', models.CharField(max_length=100)),
                ('gd_number', models.CharField(max_length=100)),
                ('ps_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
